name: irc_client
version: 0.0.3
author: James Ots <code@jamesots.com>
description: IRC client library
homepage: https://github.com/jamesots/irc_client
documentation: http://jamesots.github.io/irc_client/docs/
dev_dependencies:
  unittest: any
  http: any

#dependencies:
#  unittest: any